In [1]:
import numpy as np

In [2]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("vector:",array2)
a = array2.reshape(3,5)
print("two dimensional array:",a)

vector: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
two dimensional array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
print("shape:",a.shape)
print("dimension:",a.ndim)
print("shape:",a.dtype.name)
print("shape:",a.size)
print("shape:",type(a))


shape: (3, 5)
dimension: 2
shape: int32
shape: 15
shape: <class 'numpy.ndarray'>


In [5]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x+y)
print(x-y)
print(x**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [6]:
a=np.array([1,2,3])
d=a.copy()
print(d)
b = a
c = a
b[0] = 5
print(a,b,c)

[1 2 3]
[5 2 3] [5 2 3] [5 2 3]


In [7]:
a = np.array([1,2,3,4,5,6,7])
print(a[0])
print(a[0:4])


1
[1 2 3 4]


In [8]:
reverse_array = a[::-1]
print(reverse_array)

[7 6 5 4 3 2 1]


In [11]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[:-1])
print(b[1,1])
print(b[:1])
print(b[1:])
print(b[1,1:4])
print(b[-1:])
print(b[:-1])

[[1 2 3 4 5]]
7
[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[7 8 9]
[[ 6  7  8  9 10]]
[[1 2 3 4 5]]
